name: CI - Develop (Pruebas)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Install dependencies
        run: go mod tidy

      - name: Validate Docker Build
        run: docker build -t temp-build-check .

      - name: Build
        run: go build ./...

      - name: Run tests with coverage
        run: |
          go test ./internal/... -coverprofile=coverage.out

      - name: Check coverage >= 60%
        run: |
          raw_total=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          
          total=${raw_total%.*}
          
          echo "Total coverage (integer): $total%"
          threshold=60
          
          if [ "$total" -lt "$threshold" ]; then
            echo "Error: La cobertura actual es del $total%, pero se requiere un mínimo del $threshold%"
            exit 1
          else
            echo "¡Validación exitosa! Cobertura del $total% cumple con el requisito."
          fi
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Lambda binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

      - name: Create deployment package
        run: |
          zip function.zip bootstrap

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip